/* this file was generated by linkcmd.xdt from the gnu.targets.arm
 * package
 */
INPUT(
    "/home/daniel/vrm-demos-d3-4.3.3/demos/advanced/arm-dsp/directfb_viewer_d3/ce_api/ce_api/package/cfg/ce_api_pv5T.ov5T"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/codec_engine_3_22_01_06/packages/ti/sdo/ce/image1/lib/release/imgdec1.av5T"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/codec_engine_3_22_01_06/packages/ti/sdo/ce/image1/lib/release/imgenc1.av5T"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/codec_engine_3_22_01_06/packages/ti/sdo/ce/lib/release/ce.av5T"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/codec_engine_3_22_01_06/packages/ti/sdo/ce/alg/lib/release/Algorithm_noOS.av5T"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/codec_engine_3_22_01_06/packages/ti/sdo/ce/alg/lib/release/alg.av5T"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/codec_engine_3_22_01_06/packages/ti/sdo/ce/osal/linux/lib/release/osal_linux_470.av5T"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/codec_engine_3_22_01_06/packages/ti/sdo/ce/osal/lib/release/osal.av5T"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/codec_engine_3_22_01_06/packages/ti/sdo/ce/ipc/dsplink/lib/release/ipc_syslink.av5T"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/linuxutils_3_22_00_02/packages/ti/sdo/linuxutils/cmem/lib/cmem.a470MV"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/osal_1_22_01_09/packages/ti/sdo/utils/loggers/lib/release/loggers.av5T"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/framework_components_3_22_01_07/packages/ti/sdo/fc/global/lib/release/fcsettings.av5T"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/codec_engine_3_22_01_06/packages/ti/sdo/ce/node/lib/release/node.av5T"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/codec_engine_3_22_01_06/packages/ti/sdo/ce/utils/xdm/lib/release/XdmUtils.av5T"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/syslink_2_20_02_20/packages/ti/syslink/lib/syslink.a_release"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/osal_1_22_01_09/packages/ti/sdo/xdcruntime/linux/lib/release/osal_linux_470.av5T"
    "/opt/vrmagic/vrm-d3-ezsdk/component-sources/codec_engine_3_22_01_06/packages/ti/sdo/ce/global/lib/release/cesettings.av5T"
    "/opt/ti/ti-ezsdk-5_05_02_00/component-sources/xdctools_3_23_03_53/packages/gnu/targets/arm/rtsv5T/lib/gnu.targets.arm.rtsv5T.av5T"
)

SECTIONS {
    xdc.meta (COPY) : {KEEP(*(xdc.meta))} 

}

INSERT BEFORE .gnu.attributes

