#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.GCArmv5T{1,0,4.6
#
ce_api.xv5T: package/cfg/ce_api.xv5T.mak

clean::
	-$(RM) package/cfg/ce_api.xv5T.mak
